services:
  pebble-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pebble-sdk-container
    restart: unless-stopped
    volumes:
      - ./app:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 support
      - ${XDG_RUNTIME_DIR:-/run/user/1000}/wayland-0:/run/user/1000/wayland-0:ro  # Wayland support
    environment:
      PEBBLE_TOOL_VERSION: "pebble-sdk-4.5-linux64"
      PEBBLE_SDK_VERSION: "4.3"
      NVM_VERSION: "0.35.0"
      NODE_VERSION: "18.17.1"
      NVM_DIR: "/home/pebble/.nvm"
      DISPLAY: "${DISPLAY}"
      WAYLAND_DISPLAY: "${WAYLAND_DISPLAY}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: ["zsh", "/entrypoint.sh", "zsh"]
